name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:  # Permite deploy manual

jobs:
  sync-to-huggingface:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessário para obter todo o histórico
          lfs: true       # Se usar Git LFS para ficheiros grandes

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_SPACE_NAME: ${{ secrets.HF_SPACE_NAME }}
        run: |
          # Configurar git
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Adicionar remote do Hugging Face
          git remote add hf https://huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME || true

          # Fazer push para Hugging Face (força se necessário na primeira vez)
          git push https://user:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME main --force

      - name: Deployment summary
        run: |
          echo "✅ Successfully deployed to Hugging Face Spaces!"
          echo "🔗 Space URL: https://huggingface.co/spaces/${{ secrets.HF_USERNAME }}/${{ secrets.HF_SPACE_NAME }}"
