[theme]
# Tema escuro padrão (pode ser alterado pelo toggle na UI)
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
enableCORS = false
# Port is automatically set by the platform:
# - Streamlit Cloud: 8501 (default)
# - Hugging Face Spaces: 7860 (via environment variables)
# - Local: 8501 (default)

[browser]
gatherUsageStats = false
