[theme]
# Tema escuro padrão (pode ser alterado pelo toggle na UI)
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 7860

[browser]
gatherUsageStats = false
